// Post Punk 1 — BodyPump Routine

const ROUTINE_NAME_POST_PUNK_1 = "Post Punk 1";

const TRACK_ICONS_POST_PUNK_1 = {};

const TRACK_ICON_MAP_POST_PUNK_1 = {
  "Warm Up": "warmup",
  "Squats": "squats",
  "Chest": "chest",
  "Back": "back",
  "Biceps": "biceps",
  "Triceps": "triceps",
  "Lunges": "lunges",
  "Shoulders": "shoulders",
  "Core": "core",
  "Cooldown": "cooldown",
};

const TRACKS_POST_PUNK_1 = [
  {
    id: "warmup",
    name: "Warm Up",
    song: "Midnight Dipper",
    artist: "Warmduscher",
    weight: "3.5",
    startAt: "Bass",
    introOffset: 8,
    totalDuration: 185,
    moves: [
      { type:'data', timing:"4/4", move:"Medium Curl", reps:"4", highlight:false, duration:4 },
      { type:'data', timing:"2/2/2/2", move:"Faster Curl and RDL", reps:"6", highlight:false, duration:6 },
      { type:'data', timing:"2/2/2/2", move:"Down single row", reps:"1", highlight:false, duration:1 },
      { type:'banner', move:"Switch grip", duration:8 },
      { type:'data', timing:"2/2/2/2", move:"Upright row and rdl", reps:"6", highlight:false, duration:6 },
      { type:'data', timing:"2/2/2/2", move:"Down triple slow row", reps:"3", highlight:false, duration:3 },
      { type:'banner', move:"Bar up on shoulders", duration:8 },
      { type:'data', timing:"4/4", move:"Squat", reps:"3", highlight:false, duration:3 },
      { type:'data', timing:"4/4/4/4", move:"Stagger hold squat", reps:"2", highlight:false, duration:2 },
      { type:'data', timing:"2/2", move:"Lunge left", reps:"2", highlight:false, duration:2 },
      { type:'data', timing:"2/2", move:"Lunge right", reps:"2", highlight:false, duration:2 },
      { type:'banner', move:"Bar above head", duration:8 },
      { type:'data', timing:"1/1/1/1", move:"Knee lifts", reps:"8", highlight:false, duration:6 },
    ]
  },
  {
    id: "squats",
    name: "Squats",
    song: "Essential Tremor",
    artist: "YARD",
    weight: "7.5",
    startAt: "Drums",
    introOffset: 15,
    totalDuration: 201,
    moves: [
      { type:'data', timing:"8/8", move:"Super Slow squat", reps:"2", highlight:false, duration:2 },
      { type:'data', timing:"4/4", move:"Medium squat", reps:"8", highlight:false, duration:8 },
      { type:'data', timing:"2/2/2/2", move:"Stagger squat", reps:"4", highlight:false, duration:4 },
      { type:'data', timing:"4/4", move:"Medium squat", reps:"8", highlight:false, duration:8 },
      { type:'data', timing:"2/2/2/2", move:"Stagger squat", reps:"8", highlight:false, duration:8 },
      { type:'data', timing:"4/4", move:"Medium squat", reps:"8", highlight:false, duration:8 },
      { type:'banner', move:"Rest", duration:8 },
      { type:'data', timing:"2/1/1/2", move:"Down, single bounce, up", reps:"8", highlight:false, duration:8 },
      { type:'data', timing:"2/2/2/2", move:"Stagger squat", reps:"8", highlight:false, duration:8 },
    ]
  },
  {
    id: "chest",
    name: "Chest",
    song: "One Last Dance",
    artist: "Femur",
    weight: "5kg",
    startAt: "Drums",
    introOffset: 31,
    totalDuration: 230,
    moves: [
      { type:'data', timing:"8/8", move:"Slow press", reps:"2", highlight:false, duration:2 },
      { type:'data', timing:"4/4", move:"Medium press", reps:"7", highlight:false, duration:7 },
      { type:'data', timing:"1/1/1/1", move:"Pulse for pain", reps:"8", highlight:false, duration:8 },
      { type:'data', timing:"8/8", move:"Slow presses", reps:"2", highlight:false, duration:2 },
      { type:'banner', move:"Break to oof", duration:8 },
      { type:'data', timing:"8/8", move:"Slow press", reps:"2", highlight:false, duration:2 },
      { type:'data', timing:"4/4", move:"Medium press", reps:"7", highlight:false, duration:7 },
      { type:'data', timing:"1/1/1/1", move:"Pulse for pain", reps:"8", highlight:false, duration:8 },
      { type:'data', timing:"8/8", move:"Slow press", reps:"2", highlight:false, duration:2 },
      { type:'banner', move:"Flip over", duration:8 },
      { type:'data', timing:"2/2", move:"Press ups to end", reps:"16", highlight:false, duration:16 },
    ]
  },
  {
    id: "back",
    name: "Back",
    song: "Blood On Your Doorstep",
    artist: "Chest.",
    weight: "6kg",
    startAt: "Taps",
    introOffset: 10,
    totalDuration: 220,
    moves: [
      { type:'data', timing:"6/2", move:"Slow down fast up rdl", reps:"3", highlight:false, duration:3 },
      { type:'data', timing:"2/2/2/2", move:"Down single row slow", reps:"4", highlight:false, duration:4 },
      { type:'data', timing:"4/4", move:"RDL", reps:"1", highlight:false, duration:1 },
      { type:'data', timing:"2/2/2/2", move:"Down single row slow", reps:"4", highlight:false, duration:4 },
      { type:'data', timing:"4/4", move:"RDL", reps:"2", highlight:false, duration:2 },
      { type:'data', timing:"2/2/2/2", move:"Clean press triple", reps:"2", highlight:false, duration:2 },
      { type:'data', timing:"8/8", move:"Super slow RDL", reps:"1", highlight:false, duration:1 },
      { type:'data', timing:"2/2/2/2", move:"Down single row slow", reps:"4", highlight:false, duration:4 },
      { type:'banner', move:"Break to chorus", duration:8 },
      { type:'data', timing:"2/2/2/2", move:"Clean press triple", reps:"4", highlight:false, duration:4 },
      { type:'data', timing:"6/2", move:"Slow down fast up RDL", reps:"8", highlight:false, duration:8 },
    ]
  },
  {
    id: "biceps",
    name: "Biceps",
    song: "Hunger Games",
    artist: "Bob Vylan",
    weight: "6kg",
    startAt: "Vocal",
    introOffset: 10,
    totalDuration: 220,
    moves: [
      { type:'data', timing:"8/8", move:"Slow curl", reps:"2", highlight:false, duration:2 },
      { type:'data', timing:"4/4", move:"Stagger curl", reps:"4", highlight:false, duration:4 },
      { type:'data', timing:"1/1/1/1/4/4", move:"Pulse then slow", reps:"2", highlight:false, duration:2 },
      { type:'banner', move:"Hold to vocal", duration:8 },
      { type:'data', timing:"4/4", move:"Stagger curl", reps:"4", highlight:false, duration:4 },
      { type:'data', timing:"1/1/1/1/4/4", move:"Pulse then slow", reps:"2", highlight:false, duration:2 },
      { type:'banner', move:"Break to piggy", duration:8 },
      { type:'data', timing:"8/8", move:"Super slow curl", reps:"2", highlight:false, duration:2 },
      { type:'banner', move:"Hold", duration:8 },
      { type:'data', timing:"1/1/1/1/4/4", move:"Pulse then slow", reps:"2", highlight:false, duration:2 },
      { type:'banner', move:"Rest to vocal", duration:8 },
      { type:'data', timing:"8/8", move:"Super slow", reps:"4", highlight:false, duration:4 },
      { type:'data', timing:"4/4", move:"Medium curl", reps:"8", highlight:false, duration:8 },
    ]
  },
  {
    id: "triceps",
    name: "Triceps",
    song: "One more day",
    artist: "Soft Play",
    weight: "5kg",
    startAt: "Drums",
    introOffset: 13,
    totalDuration: 167,
    moves: [
      { type:'data', timing:"4/4", move:"Dips", reps:"4", highlight:false, duration:8 },
      { type:'data', timing:"4/4/4/4", move:"Slow stagger", reps:"4", highlight:false, duration:4 },
      { type:'data', timing:"1/1/1/1", move:"Triple Pulse", reps:"4", highlight:false, duration:4 },
      { type:'data', timing:"4/4", move:"Slow Stagger", reps:"4", highlight:false, duration:4 },
      { type:'data', timing:"1/1/1/1", move:"Triple Pulse", reps:"4", highlight:false, duration:4 },
      { type:'banner', move:"Hold", duration:8 },
      { type:'data', timing:"4/4", move:"Medium", reps:"4", highlight:false, duration:4 },
      { type:'data', timing:"1/1/1/1", move:"Triple Pulse", reps:"4", highlight:false, duration:8 },
    ]
  },
  {
    id: "lunges",
    name: "Lunges",
    song: "The New Sensation",
    artist: "IDLES",
    weight: "6kg",
    startAt: "Vocal",
    introOffset: 32,
    totalDuration: 253,
    moves: [
      { type:'data', timing:"8/8", move:"Slow Lunge", reps:"2", highlight:false, duration:2 },
      { type:'data', timing:"1/1/1/1", move:"Triple bounce", reps:"4", highlight:false, duration:4 },
      { type:'data', timing:"8/8", move:"Slow Lunge", reps:"2", highlight:false, duration:2 },
      { type:'data', timing:"1/1/1/1", move:"Triple bounce", reps:"4", highlight:false, duration:4 },
      { type:'data', timing:"8/8", move:"Slow Lunge", reps:"2", highlight:false, duration:2 },
      { type:'data', timing:"1/1/1/1", move:"Triple bounce", reps:"4", highlight:false, duration:4 },
      { type:'data', timing:"8/8", move:"Slow Lunge", reps:"2", highlight:false, duration:2 },
      { type:'data', timing:"1/1/1/1", move:"Triple bounce", reps:"3", highlight:false, duration:4 },
      { type:'banner', move:"Swap legs", duration:8 },
      { type:'data', timing:"8/8", move:"Slow lunge", reps:"2", highlight:false, duration:2 },
      { type:'data', timing:"1/1/1/1", move:"Triple bounce", reps:"3", highlight:false, duration:8 },
      { type:'data', timing:"8/8", move:"Slow lunge", reps:"2", highlight:false, duration:2 },
      { type:'data', timing:"1/1/1/1", move:"Triple bounce", reps:"3", highlight:false, duration:8 },
      { type:'data', timing:"8/8", move:"Slow lunge", reps:"2", highlight:false, duration:2 },
      { type:'data', timing:"1/1/1/1", move:"Triple bounce", reps:"2", highlight:false, duration:8 },
      { type:'banner', move:"Reset and rest", duration:8 },
      { type:'data', timing:"2/2/2/2", move:"Step lunge", reps:"8", highlight:false, duration:8 },
    ]
  },
  {
    id: "shoulders",
    name: "Shoulders",
    song: "Tongue",
    artist: "Chalk",
    weight: "3kg",
    startAt: "Vocal",
    introOffset: 6,
    totalDuration: 148,
    moves: [
      { type:'data', timing:"8/8", move:"Single rtw", reps:"4", highlight:false, duration:16 },
      { type:'banner', move:"Hold to verse", duration:8 },
      { type:'data', timing:"4/4", move:"Lateral raise", reps:"4", highlight:false, duration:16 },
      { type:'data', timing:"4/4/4/4", move:"Side front side down", reps:"2", highlight:false, duration:16 },
      { type:'data', timing:"8/8", move:"Round the world", reps:"2", highlight:false, duration:16 },
      { type:'banner', move:"Hold", duration:8 },
      { type:'data', timing:"4/4", move:"Lateral raise", reps:"4", highlight:false, duration:16 },
      { type:'data', timing:"4/4/4/4", move:"Side front side down", reps:"4", highlight:false, duration:16 },
      { type:'data', timing:"8/8", move:"Round the world", reps:"3", highlight:false, duration:16 },
    ]
  },
  {
    id: "core",
    name: "Core",
    song: "Look At Me",
    artist: "Jehnny Beth",
    weight: "N/A",
    startAt: "Vocal",
    introOffset: 7,
    totalDuration: 177,
    moves: [
      { type:'data', timing:"4/4/4/4", move:"Pull in, tip back", reps:"4", highlight:false, duration:16 },
      { type:'data', timing:"2/2", move:"Slow bicycles", reps:"8", highlight:false, duration:16 },
      { type:'data', timing:"1/1", move:"Pulse", reps:"8", highlight:false, duration:16 },
      { type:'data', timing:"4/4/4/4", move:"Pull in, tip back", reps:"3", highlight:false, duration:16 },
      { type:'data', timing:"2/2", move:"Slow bicycles", reps:"8", highlight:false, duration:16 },
      { type:'banner', move:"Pause and flip to plank", duration:8 },
      { type:'data', timing:"2/2/2/2", move:"Out in legs", reps:"4", highlight:false, duration:16 },
      { type:'data', timing:"2/2/2/2", move:"Mountain climbers", reps:"8", highlight:false, duration:16 },
      { type:'data', timing:"", move:"Plank to end", reps:"", highlight:false, duration:16 },
    ]
  },
];

const BREAK_AFTER_POST_PUNK_1 = {
  "warmup": null,
  "squats": null,
  "chest": null,
  "back": null,
  "biceps": null,
  "triceps": null,
  "lunges": null,
  "shoulders": null,
  "core": 60,
};

window.ROUTINES = window.ROUTINES || [];
window.ROUTINES.push({
  name: ROUTINE_NAME_POST_PUNK_1,
  font: null,
  tracks: TRACKS_POST_PUNK_1,
  icons: TRACK_ICONS_POST_PUNK_1,
  iconMap: TRACK_ICON_MAP_POST_PUNK_1,
  breakAfter: BREAK_AFTER_POST_PUNK_1,
});
