// Bodypump 10 — BodyPump Routine
// To add a new routine, copy this file, edit the data, and add an entry to routines/index.json

const ROUTINE_NAME_10 = 'Bodypump 10';

const TRACK_ICONS_10 = {};

const TRACK_ICON_MAP_10 = {
  'Warm Up':   'warmup',
  'Squats':    'squats',
  'Chest':     'chest',
  'Back':      'back',
  'Biceps':    'biceps',
  'Triceps':   'triceps',
  'Lunges':    'lunges',
  'Shoulders': 'shoulders',
  'Core':      'abs',
  'Cooldown':  'cooldown',
};

const TRACKS_10 = [
  {
    id: 'warmup',
    name: 'Warm Up',
    song: 'Cognitive Trade-Off',
    artist: 'Viagra Boys',
    weight: '3.75kg x 2',
    startAt: 'Vocal',
    introOffset: 15,
    totalDuration: 240,
    moves: [
      { type:'data', timing:'8/8',     move:'Slow bicep curl',              reps:'2',  highlight:false, duration:20 },
      { type:'data', timing:'4/4',     move:'Medium bicep curl',            reps:'4',  highlight:false, duration:20 },
      { type:'data', timing:'1/1/1/1', move:'D Lift single row',            reps:'4',  highlight:true,  duration:16 },
      { type:'banner', move:'Switch grip', duration:4 },
      { type:'data', timing:'2/2',     move:'Upright rows',                 reps:'2',  highlight:false, duration:10 },
      { type:'data', timing:'8/8',     move:'Dead lift slow',               reps:'2',  highlight:false, duration:20 },
      { type:'data', timing:'4/4',     move:'Medium RDL',                   reps:'4',  highlight:false, duration:20 },
      { type:'data', timing:'1/1/1/1', move:'Doubles RDL row, clean & press', reps:'6', highlight:true, duration:24 },
      { type:'banner', move:'Bar on shoulders', duration:8 },
      { type:'data', timing:'8/8',     move:'Slow squats',                  reps:'2',  highlight:false, duration:20 },
      { type:'data', timing:'2/2',     move:'Lunge left',                   reps:'7',  highlight:false, duration:18 },
      { type:'data', timing:'2/2',     move:'Lunge right',                  reps:'7',  highlight:false, duration:18 },
      { type:'data', timing:'4/4',     move:'Medium squats',                reps:'4',  highlight:false, duration:20 },
    ]
  },
  {
    id: 'squats',
    name: 'Squats',
    song: 'Diva',
    artist: 'Model/Actriz',
    weight: '8.5kg x 2',
    startAt: 'Drums',
    introOffset: 15,
    totalDuration: 210,
    moves: [
      { type:'data', timing:'8/8',     move:'Super slow squat intro',       reps:'4',  highlight:false, duration:32 },
      { type:'data', timing:'1/1/1/1', move:'Stagger squat',                reps:'4',  highlight:true,  duration:16 },
      { type:'banner', move:'Break — wiggle to bitch', duration:8 },
      { type:'data', timing:'1/1',     move:'Pulse',                        reps:'15', highlight:false, duration:16 },
      { type:'banner', move:'Release and repeat', duration:4 },
      { type:'data', timing:'1/1/1/1', move:'Stagger squat',                reps:'4',  highlight:true,  duration:16 },
      { type:'banner', move:'Break to next one', duration:6 },
      { type:'data', timing:'1/3',     move:'Fast down slow up',            reps:'2',  highlight:false, duration:8 },
      { type:'banner', move:'Break — something more', duration:8 },
      { type:'data', timing:'1/1/1/1', move:'Stagger squat',                reps:'8',  highlight:true,  duration:32 },
      { type:'data', timing:'8/8',     move:'Super slow squat to end',      reps:'8',  highlight:false, duration:64 },
    ]
  },
  {
    id: 'chest',
    name: 'Chest',
    song: 'Samaritans',
    artist: 'IDLES',
    weight: '5kg x 2',
    startAt: 'Vocal',
    introOffset: 15,
    totalDuration: 250,
    moves: [
      { type:'data', timing:'8/8',     move:'Slow press',                   reps:'1',  highlight:false, duration:16 },
      { type:'data', timing:'4/4',     move:'Medium press',                 reps:'1',  highlight:false, duration:8 },
      { type:'banner', move:'Repeat', duration:4 },
      { type:'data', timing:'1/1/1/1', move:'Stagger press — The Mask',     reps:'3',  highlight:true,  duration:12 },
      { type:'data', timing:'1/1',     move:'Pulse — Real Boy',             reps:'4',  highlight:false, duration:8 },
      { type:'data', timing:'4/4',     move:'Single and skullcrusher',      reps:'3',  highlight:false, duration:12 },
      { type:'banner', move:'REST', duration:12 },
      { type:'data', timing:'8/8',     move:'Slow press',                   reps:'1',  highlight:false, duration:16 },
      { type:'data', timing:'4/4',     move:'Medium press',                 reps:'1',  highlight:false, duration:8 },
      { type:'data', timing:'1/1/1/1', move:'Stagger press — The Mask',     reps:'3',  highlight:true,  duration:12 },
      { type:'data', timing:'1/1',     move:'Pulse — Real Boy',             reps:'4',  highlight:false, duration:8 },
      { type:'data', timing:'4/4',     move:'Single and skullcrusher',      reps:'3',  highlight:false, duration:12 },
      { type:'data', timing:'2/2',     move:'Flip to push-ups — I Kissed',  reps:'10', highlight:true,  duration:20 },
    ]
  },
  {
    id: 'back',
    name: 'Back',
    song: 'Cut Hands',
    artist: 'Deftones',
    weight: '7.5kg x 2',
    startAt: 'Guitar',
    introOffset: 15,
    totalDuration: 200,
    moves: [
      { type:'data', timing:'6/4',     move:'Awkward D lift',               reps:'3',  highlight:false, duration:24 },
      { type:'data', timing:'1/1/1/1', move:'D lift rows',                  reps:'7',  highlight:true,  duration:28 },
      { type:'data', timing:'6/4',     move:'Awkward D lift',               reps:'4',  highlight:false, duration:32 },
      { type:'data', timing:'1/1/1/1', move:'D lift rows',                  reps:'6',  highlight:true,  duration:24 },
      { type:'banner', move:'Break', duration:8 },
      { type:'data', timing:'',        move:'Clean and press',              reps:'6',  highlight:false, duration:24 },
      { type:'data', timing:'1/1/1/1', move:'D lift rows',                  reps:'7',  highlight:true,  duration:28 },
      { type:'data', timing:'',        move:'Clean and press',              reps:'7',  highlight:false, duration:28 },
    ]
  },
  {
    id: 'biceps',
    name: 'Biceps',
    song: 'Jacked',
    artist: 'Heartworms',
    weight: 'Warm up weight!!',
    startAt: 'Guitars',
    introOffset: 15,
    totalDuration: 230,
    moves: [
      { type:'data', timing:'8/8',     move:'Super slow curl intro',        reps:'2',  highlight:false, duration:32 },
      { type:'data', timing:'4/4',     move:'Med curl, stagger down on 2nd',reps:'8',  highlight:false, duration:32 },
      { type:'data', timing:'1/1/1/1', move:'Pulse',                        reps:'15', highlight:false, duration:16 },
      { type:'banner', move:'PAUSE', duration:8 },
      { type:'data', timing:'8/8',     move:'Slow curl',                    reps:'4',  highlight:false, duration:32 },
      { type:'data', timing:'1/1/1/1', move:'Pulse',                        reps:'15', highlight:false, duration:16 },
      { type:'banner', move:'REST to vocal', duration:8 },
      { type:'data', timing:'8/8',     move:'Slow curl',                    reps:'4',  highlight:false, duration:32 },
      { type:'banner', move:'REST', duration:8 },
      { type:'data', timing:'4/4',     move:'Med curl, stagger down on 2nd',reps:'4',  highlight:false, duration:16 },
      { type:'banner', move:'REST to chaos', duration:8 },
      { type:'data', timing:'1/1/1/1', move:'Pulse',                        reps:'32', highlight:true,  duration:32 },
    ]
  },
  {
    id: 'triceps',
    name: 'Triceps',
    song: 'Going Clear',
    artist: 'Chest.',
    weight: '5kg',
    startAt: 'Bass',
    introOffset: 15,
    totalDuration: 220,
    moves: [
      { type:'data', timing:'8/8',     move:'Slow overhead extension',      reps:'2',  highlight:false, duration:32 },
      { type:'data', timing:'4/4',     move:'Medium overhead extension',    reps:'8',  highlight:false, duration:32 },
      { type:'banner', move:'Repeat verse', duration:4 },
      { type:'data', timing:'1/1',     move:'Pulse short',                  reps:'4',  highlight:false, duration:8 },
      { type:'data', timing:'4/4',     move:'Medium overhead extension',    reps:'4',  highlight:false, duration:16 },
      { type:'data', timing:'1/1',     move:'Pulse',                        reps:'15', highlight:false, duration:16 },
      { type:'data', timing:'1/1/1/1', move:'Stagger',                      reps:'4',  highlight:true,  duration:16 },
      { type:'banner', move:'REST', duration:8 },
      { type:'data', timing:'8/8',     move:'Slow overhead extension',      reps:'2',  highlight:false, duration:32 },
      { type:'data', timing:'1/1',     move:'Pulse',                        reps:'15', highlight:false, duration:16 },
      { type:'data', timing:'1/1/1/1', move:'Stagger',                      reps:'8',  highlight:true,  duration:32 },
    ]
  },
  {
    id: 'lunges',
    name: 'Lunges',
    song: 'Are You Satisfied?',
    artist: 'Soft Play',
    weight: '7.5kg x 2',
    startAt: 'Vocal',
    introOffset: 15,
    totalDuration: 215,
    moves: [
      { type:'data', timing:'4/4',     move:'Slow lunge',                   reps:'4',  highlight:false, duration:16 },
      { type:'data', timing:'1/1',     move:'Bounce sockets',               reps:'7',  highlight:false, duration:8 },
      { type:'data', timing:'2/2',     move:'Medium lunge',                 reps:'7',  highlight:false, duration:14 },
      { type:'banner', move:'SWAP LEGS', duration:4 },
      { type:'data', timing:'4/4',     move:'Slow lunge',                   reps:'4',  highlight:false, duration:16 },
      { type:'data', timing:'1/1',     move:'Bounce sockets',               reps:'7',  highlight:false, duration:8 },
      { type:'data', timing:'2/2',     move:'Medium lunge (pockets)',       reps:'7',  highlight:false, duration:14 },
      { type:'banner', move:'SWAP LEGS', duration:4 },
      { type:'data', timing:'2/2',     move:'Medium lunge',                 reps:'4',  highlight:false, duration:8 },
      { type:'data', timing:'1/1',     move:'Bounce sockets',               reps:'8',  highlight:false, duration:8 },
      { type:'data', timing:'2/2',     move:'Medium lunge',                 reps:'4',  highlight:false, duration:8 },
      { type:'data', timing:'1/1',     move:'Bounce sockets',               reps:'8',  highlight:false, duration:8 },
    ]
  },
  {
    id: 'shoulders',
    name: 'Shoulders',
    song: 'Until You Showed Me',
    artist: 'CLT DRP',
    weight: '3kg x 2',
    startAt: 'Vocal',
    introOffset: 15,
    totalDuration: 200,
    moves: [
      { type:'data', timing:'4/4',     move:'Lat raises',                   reps:'4',  highlight:false, duration:16 },
      { type:'data', timing:'2/2/2/2', move:'Alt front side front down',    reps:'4',  highlight:false, duration:16 },
      { type:'data', timing:'1/1/1/1', move:'Double front vertical pump',   reps:'1',  highlight:false, duration:4 },
      { type:'data', timing:'4/4',     move:'Lat raises',                   reps:'4',  highlight:false, duration:16 },
      { type:'data', timing:'2/2/2/2', move:'Alt front side front down',    reps:'4',  highlight:false, duration:16 },
      { type:'data', timing:'1/1/1/1', move:'Double front vertical pump',   reps:'32', highlight:true,  duration:32 },
      { type:'data', timing:'1/3',     move:'Fast up on 2, slow down',      reps:'4',  highlight:false, duration:16 },
      { type:'data', timing:'1/1/1/1', move:'Double front vertical pump',   reps:'16', highlight:true,  duration:16 },
    ]
  },
  {
    id: 'core',
    name: 'Core',
    song: 'Crossing Guard',
    artist: 'Model/Actriz',
    weight: 'No weight',
    startAt: "At 'ah'",
    introOffset: 10,
    totalDuration: 190,
    moves: [
      { type:'data', timing:'4/4',     move:'Slow crunch',                  reps:'2',  highlight:false, duration:16 },
      { type:'data', timing:'2/2',     move:'Crunch',                       reps:'4',  highlight:false, duration:16 },
      { type:'data', timing:'1/1',     move:'Side crunch pulses',           reps:'16', highlight:false, duration:16 },
      { type:'banner', move:'REST chorus', duration:16 },
      { type:'data', timing:'4/4',     move:'Slow crunch',                  reps:'2',  highlight:false, duration:16 },
      { type:'data', timing:'2/2',     move:'Crunch',                       reps:'4',  highlight:false, duration:16 },
      { type:'data', timing:'1/1',     move:'Side crunch pulses',           reps:'16', highlight:false, duration:16 },
      { type:'banner', move:'REST chorus', duration:16 },
      { type:'banner', move:'Flip to plank after crosses', duration:8 },
      { type:'data', timing:'',        move:'Out in feet, alt start side',  reps:'',   highlight:false, duration:20 },
      { type:'data', timing:'',        move:'Plank to fail',                reps:'',   highlight:true,  duration:30 },
    ]
  },
  {
    id: 'cooldown',
    name: 'Cooldown',
    song: 'If This Is Life',
    artist: 'Meryl Streek',
    weight: 'No weight',
    startAt: 'Drums',
    introOffset: 10,
    totalDuration: 180,
    moves: [
      { type:'banner', move:'Stretches — follow your body', duration:170 },
    ]
  },
];

const BREAK_AFTER_10 = {
  'warmup':    60,
  'squats':    60,
  'chest':     60,
  'back':      60,
  'biceps':    60,
  'triceps':   60,
  'lunges':    60,
  'shoulders': 60,
  'core':      null,
  'cooldown':  null,
};

window.ROUTINES = window.ROUTINES || [];
window.ROUTINES.push({
  name: ROUTINE_NAME_10,
  font: null,
  tracks: TRACKS_10,
  icons: TRACK_ICONS_10,
  iconMap: TRACK_ICON_MAP_10,
  breakAfter: BREAK_AFTER_10,
});
